version: '3.3'
services:
  docker:
    image: docker-service-report:${VERSAO}
    env_file: .env-prod
    ports:
      - "4005:4005"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./files:/monitor/files
      - ./logs:/monitor/logs
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - SERVER_IP=${SERVER_IP}
      - PREFIX=${PREFIX}
      - VERSAO=${VERSAO}
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
      restart_policy:
        condition: on-failure
    networks:
      - report_network

networks:
  report_network:
    driver: overlay
