services:
  docker:
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file: .env
    ports:
      - "5005:4005"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/loadavg:/host_proc_loadavg:ro
      - /proc/uptime:/host_proc_uptime:ro
      - ./:/monitor
    environment:
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - SERVER_IP=${SERVER_IP}
      - PREFIX=${PREFIX}
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
      restart_policy:
        condition: on-failure
    networks:
      - report_network

networks:
  report_network:
    driver: bridge
