name: Deploy Docker Monitor

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure Swarm active
        run: |
          SWARM_STATUS=$(docker info --format '{{.Swarm.LocalNodeState}}')
          echo "Current Swarm status: $SWARM_STATUS"
          if [ "$SWARM_STATUS" != "active" ]; then
            docker swarm init
          fi

      - name: Setup UV (Python universal runner)
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run Python tests via uvx
        run: |
          uvx pytest -v --maxfail=1 --disable-warnings || exit 1

      - name: Build Docker image
        run: |
          docker build -t docker-monitor -f Dockerfile.local .

      - name: Deploy stack on Swarm
        run: |
          docker stack deploy -c docker-compose.swarm.yml stack_monitor

      - name: Check service status
        run: docker service ls
