name: Deploy Docker Monitor Stack

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  deploy:
    name: Deploy to Docker Swarm (GCP CloudShell)
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Docker is available
        run: |
          docker version || (echo "Docker not found!" && exit 1)
          docker info

      - name: Initialize Swarm and deploy
        run: |
          set -e
          echo "=== Checking Swarm status ==="
          SWARM_STATUS=$(docker info --format '{{.Swarm.LocalNodeState}}')
          echo "Current Swarm status: $SWARM_STATUS"
          if [ "$SWARM_STATUS" != "active" ]; then
              echo "Initializing Docker Swarm..."
              docker swarm init || true
          fi
          echo "=== Building Monitor image ==="
          docker build -t docker-monitor .
          echo "=== Deploying stack ==="
          docker stack deploy -c docker-compose.yml stack_monitor
          echo "=== Done! ==="
